import jsPDF from 'jspdf'

export async function exportToPDF(title: string, markdownContent: string) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const maxWidth = pageWidth - margin * 2
  let y = margin

  // Title
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(title, margin, y)
  y += 12

  // Separator line
  doc.setDrawColor(200, 200, 200)
  doc.line(margin, y, pageWidth - margin, y)
  y += 8

  // Content
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')

  const lines = markdownContent.split('\n')

  for (const line of lines) {
    const trimmed = line.trim()

    // Check if we need a new page
    if (y > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage()
      y = margin
    }

    if (trimmed.startsWith('# ')) {
      y += 4
      doc.setFontSize(16)
      doc.setFont('helvetica', 'bold')
      doc.text(trimmed.replace(/^#+\s*/, ''), margin, y)
      y += 8
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
    } else if (trimmed.startsWith('## ')) {
      y += 3
      doc.setFontSize(13)
      doc.setFont('helvetica', 'bold')
      doc.text(trimmed.replace(/^#+\s*/, ''), margin, y)
      y += 7
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
    } else if (trimmed.startsWith('### ')) {
      y += 2
      doc.setFontSize(11)
      doc.setFont('helvetica', 'bold')
      doc.text(trimmed.replace(/^#+\s*/, ''), margin, y)
      y += 6
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
    } else if (trimmed === '') {
      y += 3
    } else {
      // Clean markdown syntax for plain text
      const cleaned = trimmed
        .replace(/\*\*(.*?)\*\*/g, '$1')
        .replace(/\*(.*?)\*/g, '$1')
        .replace(/`(.*?)`/g, '$1')

      const splitLines = doc.splitTextToSize(cleaned, maxWidth)
      doc.text(splitLines, margin, y)
      y += splitLines.length * 5
    }
  }

  // Footer
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(
      `Generated by Clarispec — Page ${i} of ${totalPages}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    )
    doc.setTextColor(0)
  }

  doc.save(`${title.replace(/\s+/g, '_')}.pdf`)
}
